[versions]
agp = "8.13.0"
blueprint = "1.1.52"
coreSplashscreen = "1.0.1"
ffmpegKitMin = "6.0-2"
firebaseCrashlyticsGradle = "3.0.6"
fragmentKtx = "1.8.9"
googleFirebaseBom = "33.16.0"
gson = "2.13.2"
jiebaAnalysis = "1.0.2"
jsoup = "1.21.2"
juniversalchardet = "1.0.3"
exifinterface = "1.4.1"
kotlin = "2.2.10"
google-services="4.4.4"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
glideVersion = "5.0.5"
lottieVersion = "6.6.10"
material = "1.12.0"
constraintlayout = "2.2.1"
activity = "1.9.3"
persistentcookiejar = "1.0.1"
room = "2.8.1"
speedDial = "3.3.0"
sqliteJdbc = "3.50.3.0"
subsamplingScaleImageViewAndroidx = "3.10.0"
swiperefreshlayout = "1.1.0"
ksp = "2.3.3"
lifecycleLivedataKtx = "2.9.4"
lifecycleViewmodelKtx = "2.9.4"
threetenabp = "1.4.9"
workRuntimeKtx = "2.9.1"
vico = "2.0.0-alpha.5"
slf4j-simple = "2.0.17"
log4j-core = "2.25.2"
poi = "5.4.1"

[libraries]
android-lottie = { module = "com.airbnb.android:lottie", version.ref = "lottieVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
avif-integration = { module = "com.github.bumptech.glide:avif-integration", version.ref = "glideVersion" }
blueprint = { module = "io.github.xiaoyvyv:blueprint", version.ref = "blueprint" }
blueprint-floater = { module = "io.github.xiaoyvyv:floater", version.ref = "blueprint" }
ffmpeg-kit-min = { module = "com.arthenica:ffmpeg-kit-min", version.ref = "ffmpegKitMin" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "googleFirebaseBom" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glideVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jieba-analysis = { module = "com.huaban:jieba-analysis", version.ref = "jiebaAnalysis" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
juniversalchardet = { module = "com.googlecode.juniversalchardet:juniversalchardet", version.ref = "juniversalchardet" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
persistent-cookie-jar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "persistentcookiejar" }
speed-dial = { module = "com.leinardi.android:speed-dial", version.ref = "speedDial" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }
subsampling-scale-image-view-androidx = { module = "com.davemorrissey.labs:subsampling-scale-image-view-androidx", version.ref = "subsamplingScaleImageViewAndroidx" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }
vico-core = { group = "com.patrykandpatrick.vico", name = "core", version.ref = "vico" }
vico-views = { group = "com.patrykandpatrick.vico", name = "views", version.ref = "vico" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j-core" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-simple" }
poi = { module = "org.apache.poi:poi", version.ref = "poi" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }

